channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alembic=1.4.2
  - async_generator=1.10
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.4
  - blinker=1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - certipy=0.1.3
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - configurable-http-proxy=4.0.1
  - cryptography=2.9.2
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - flask=1.1.2
  - flask-sqlalchemy=2.4.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterhub=1.0.0
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mako=1.1.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - nodejs=6.11.2
  - notebook=6.0.3
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - pamela=1.0.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pycurl=7.43.0.5
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - sqlalchemy=1.3.16
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - flask-migrate==2.5.3