"""Changed grading

Revision ID: 9f26292863be
Revises: a5f9c63cdb64
Create Date: 2020-06-07 23:22:00.889274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f26292863be'
down_revision = 'a5f9c63cdb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('graded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'graded')
    # ### end Alembic commands ###
