"""Added external submission id

Revision ID: a5f9c63cdb64
Revises: e24786819569
Create Date: 2020-06-06 12:22:18.856324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f9c63cdb64'
down_revision = 'e24786819569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('external_identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'external_identifier')
    # ### end Alembic commands ###
