"""Add git_url column

Revision ID: adbb81aaff81
Revises: dd9513a1f3f1
Create Date: 2020-05-08 23:43:27.424215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbb81aaff81'
down_revision = 'dd9513a1f3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('git_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'git_url')
    # ### end Alembic commands ###
