"""Remove max_score column

Revision ID: dd9513a1f3f1
Revises: ea61fad81ba8
Create Date: 2020-05-08 21:32:33.432240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd9513a1f3f1"
down_revision = "ea61fad81ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contents") as batch_op:
        batch_op.drop_column("max_score")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("max_score", sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
