"""Added Submissions

Revision ID: e24786819569
Revises: adbb81aaff81
Create Date: 2020-06-04 23:05:48.568322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24786819569'
down_revision = 'adbb81aaff81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('content_slug', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_slug'], ['contents.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('notebooks',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('submission_slug', sa.String(length=32), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submission_slug'], ['submissions.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebooks')
    op.drop_table('submissions')
    # ### end Alembic commands ###
