"""Added score and max_score

Revision ID: fcd99f35aa73
Revises: 9f26292863be
Create Date: 2020-06-11 15:54:24.423360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd99f35aa73'
down_revision = '9f26292863be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('score', sa.Float(), nullable=False))
    op.drop_column('submissions', 'graded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('graded', sa.BOOLEAN(), nullable=False))
    op.drop_column('notebooks', 'score')
    # ### end Alembic commands ###
